In [ ]:
#cantumkan semau modul/packages/library yang digunakan ke jurnal

In [103]:
!pip install google-cloud-language

   ---------------------------------------- 0.0/138.7 kB ? eta -:--:--
   -- ------------------------------------- 10.2/138.7 kB ? eta -:--:--
   -- ------------------------------------- 10.2/138.7 kB ? eta -:--:--
   ----------------- --------------------- 61.4/138.7 kB 550.5 kB/s eta 0:00:01
   ---------------------------------------- 138.7/138.7 kB 1.0 MB/s eta 0:00:00


In [84]:
!pip install textblob

In [8]:
!pip install google-cloud-storage google-cloud-translate pandas

   ---------------------------------------- 0.0/121.1 kB ? eta -:--:--
   ---------- ----------------------------- 30.7/121.1 kB ? eta -:--:--
   ------------- ------------------------- 41.0/121.1 kB 991.0 kB/s eta 0:00:01
   ----------------------------- --------- 92.2/121.1 kB 751.6 kB/s eta 0:00:01
   -------------------------------------- 121.1/121.1 kB 887.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/80.3 kB ? eta -:--:--
   ---------------------------------------- 80.3/80.3 kB 4.4 MB/s eta 0:00:00


In [2]:
!pip install twscrape

  Obtaining dependency information for twscrape from https://files.pythonhosted.org/packages/af/36/10a72649b893c93f5bf7f9e186bd1cfafa99d325efa02f0981c38da76689/twscrape-0.9.0-py3-none-any.whl.metadata
  Obtaining dependency information for fake-useragent>=1.3.0 from https://files.pythonhosted.org/packages/33/c9/ff44922639b8827dbc86d463d870dabfc19d1567d8a6427dcb2289d83fd8/fake_useragent-1.4.0-py3-none-any.whl.metadata
  Obtaining dependency information for httpx>=0.24.0 from https://files.pythonhosted.org/packages/a2/65/6940eeb21dcb2953778a6895281c179efd9100463ff08cb6232bb6480da7/httpx-0.25.2-py3-none-any.whl.metadata
  Obtaining dependency information for loguru>=0.7.0 from https://files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl.metadata
  Obtaining dependency information for anyio from https://files.pythonhosted.org/packages/85/4f/d010eca6914703d8e6be222165d02c3e708ed909cdb2b7af3743667f302e/anyio-4.1.0-py

In [15]:
!pip install openpyxl


     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     ------ ------------------------------ 41.0/250.0 kB 495.5 kB/s eta 0:00:01
     ---------- -------------------------- 71.7/250.0 kB 563.7 kB/s eta 0:00:01
     ----------------------------- -------- 194.6/250.0 kB 1.2 MB/s eta 0:00:01
     -------------------------------------- 250.0/250.0 kB 1.2 MB/s eta 0:00:00


In [9]:
!pip install scikit-learn

     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     -------------------------------- ----- 51.2/60.4 kB 650.2 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 796.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.2 MB 1.9 MB/s eta 0:00:05
   - -------------------------------------- 0.2/9.2 MB 2.9 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/9.2 MB 3.8 MB/s eta 0:00:03
   --- ------------------------------------ 0.7/9.2 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 0.9/9.2 MB 4.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.2/9.2 MB 4.6 MB/s eta 0:00:02
   ------ --------------------------------- 1.5/9.2 MB 4.7 MB/s eta 0:00:02
   ------- -------------------------------- 1.7/9.2 MB 4.8 MB/s eta 0:00:02
   -------- ------

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates from a subpr

In [2]:
pip install nest_asyncio

Note: you may need to restart the kernel to use updated packages.


In [28]:
!pip install google-cloud-translate

     ---------------------------------------- 0.0/181.3 kB ? eta -:--:--
     ------ -------------------------------- 30.7/181.3 kB 1.4 MB/s eta 0:00:01
     ------------------------- ------------ 122.9/181.3 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 181.3/181.3 kB 1.8 MB/s eta 0:00:00
   ---------------------------------------- 0.0/128.9 kB ? eta -:--:--
   ---------------------------------------- 128.9/128.9 kB 7.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/122.2 kB ? eta -:--:--
   ---------------------------------------- 122.2/122.2 kB 7.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/48.1 kB ? eta -:--:--
   ---------------------------------------- 48.1/48.1 kB 2.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/413.4 kB ? eta -:--:--
   ---------------- ---------------------- 174.1/413.4 kB 10.9 MB/s eta 0:00:01
   ------------------- -------------------- 204.8/413.4 kB 2.5 MB/s eta 0:00:01
   ---

In [9]:
!pip install --upgrade googletrans

  Using cached httpx-0.13.3-py3-none-any.whl (55 kB)
  Using cached httpcore-0.9.1-py3-none-any.whl (42 kB)
  Using cached h11-0.9.0-py2.py3-none-any.whl (53 kB)
  Attempting uninstall: h11
    Found existing installation: h11 0.14.0
    Uninstalling h11-0.14.0:
      Successfully uninstalled h11-0.14.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.2
    Uninstalling httpcore-1.0.2:
      Successfully uninstalled httpcore-1.0.2
  Attempting uninstall: httpx
    Found existing installation: httpx 0.25.2
    Uninstalling httpx-0.25.2:
      Successfully uninstalled httpx-0.25.2


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
twscrape 0.9.0 requires httpx>=0.24.0, but you have httpx 0.13.3 which is incompatible.


In [1]:
#asyncio adalah library yang berfungsi untuk menghandle berbagai i/o tanpa perlu menunggu program sebelumnya selesai dijalankan di program
import nest_asyncio
import asyncio
from twscrape import API, gather
from twscrape.logger import set_log_level
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
nest_asyncio.apply()

In [27]:
async def xxx(count, max_tweets):
    api = API()  # Replace with your API instantiation

    tweet_list = []

    await api.pool.login_all()

    # API USAGE

    # Search tweets based on keywords
    tweets = await gather(api.search("pilpres OR capres OR pemilu OR prabowo OR anies OR ganjar", limit=10000))
    
    for tweet in tweets:
        tweet_list.append({
            "tweet_id": tweet.id,
            "username": tweet.user.username,
            "content": tweet.rawContent,
            "retweets" : tweet.retweetCount,
            "likes": tweet.likeCount
        })

    # Convert tweet list to DataFrame
    tweet_df = pd.DataFrame(tweet_list)
    return tweet_df


In [20]:
async def fetch_tweets():
    api = API()  # Replace with your API instantiation
    tweet_list = []

    await api.pool.login_all()

# API USAGE
# Search tweets based on keywords with pagination
    tweets = await gather(api.search("prabowo OR anies OR ganjar", limit =1000))

    for tweet in tweets:
        tweet_list.append({
            "tweet_id": tweet.id,
            "username": tweet.user.username,
            "content": tweet.rawContent,
            "retweets" : tweet.retweetCount,
            "likes": tweet.likeCount
        })


# Convert tweet list to DataFrame
    tweet_df = pd.DataFrame(tweet_list)
    return tweet_df

In [94]:
tweets_df = pd.read_excel("tweets3.xlsx")

In [ ]:
#mungkin bisa satu2 fetch 1000 data setiap kandidat agar adil, setelah preprocessing dan classification analysis selesai dilakukan 

In [21]:
tweet_df = asyncio.run(fetch_tweets())

2023-12-01 21:55:24.926 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:260 - No account available for queue "SearchTimeline". Next available at 22:08:14
2023-12-01 22:08:16.460 | INFO     | twscrape.accounts_pool:get_for_queue_or_wait:266 - Account available for queue SearchTimeline


In [4]:
tweets_df

tweet_id         username  \
0    1730587179322405120  Tokobarokahjaya   
1    1730587179041313024    rizkypuetraaa   
2    1730587178709958912       orangOedik   
3    1730587167003700992       luffyphile   
4    1730587163442708992     AiraGreselya   
..                   ...              ...   
665  1730584689365434880  yosephermawan17   
666  1730584678493536000       Heraloebss   
667  1730578327289861120  AchmadShonnyArc   
668  1730584677403255040    trilestaritky   
669  1730584677055184896  RondangKomariah   

                                               content  retweets  likes  
0    @ganjarpranowo wah pake penyambutan adat  , me...         0      0  
1    @TuaJalanJalan @sleepinight @PartaiSocmed @Tua...         0      0  
2    @ferizandra Bang jgn gt lah...coba kita tabayu...         0      0  
3    @tvOneNews Salut sama pak ganjar, apapun yang ...         0      0  
4    @tvOneNews Pak Ganjar Mahfud pilihan yang tepa...         0      0  
..                                                 ...       ...    ...  
665    @tvOneNews Kawall Ganjar Mahfud MD sampe m3nang         0      0  
666  Mohon izin Posting Video panjang Pak @prabowo ...        15     34  
667  @Heraloebss Just following digital record hone...         0      1  
668  @voiceofpkb Bersama pasangan Anies Muhaimin wu...         0      0  
669  Prabowo Cinta Rakyat Ketua TKD Jabar Ridwan Ka...         8      0  

[670 rows x 5 columns]

In [7]:
tweets_df = pd.read_excel("tweetsfix2.xlsx")

## Data preprocessing

### Remove unnecessary content (tag, link,emoticon,etc)

In [5]:
def clean_contents(content, exceptions):
    # Create patterns for mentions, URLs, emoticons, hashtags, and other characters
    mention_pattern = re.compile(r'@\w+')
    url_pattern = re.compile(r'https?://\S+')
    emoticon_pattern = re.compile(r'\S*?(\:\)|\:\(|\:D|\;\)|\<3|\:\*\))')
    hashtag_pattern = re.compile(r'#\w+')
    other_pattern = re.compile(r'[^\s\w@]|_|\b\d+\b')

    # Combine all patterns
    combined_pattern = re.compile(f'({mention_pattern.pattern}|{url_pattern.pattern}|{emoticon_pattern.pattern}|{hashtag_pattern.pattern}|{other_pattern.pattern})')

    # Use re.sub to replace matching patterns with an empty string
    cleaned_text = combined_pattern.sub(lambda match: match.group(1) if match.group(1) and match.group(1) in exceptions else '', content)

    # Remove unnecessary spaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()

    return cleaned_text




In [8]:
exception_list = ['gibran', 'ganjar', 'prabowo', 'anies','PakbowoGibran', 'Gangar']
cleaned_contents_np = np.array([])
for content in tweets_df['content']:
    cleaned_content = clean_contents(content, exception_list)
    cleaned_contents_np = np.append(cleaned_contents_np, cleaned_content)

In [9]:
print(cleaned_contents_np)

['wah pake penyambutan adat menggambarkan kalau pak ganjar di terima dengan baik'
 'lha gw ngedukung prabowo lalu dicap buzzer Wkwkwkwkw tuduhannya ga masuk akal tolol'
 'Bang jgn gt lahcoba kita tabayunbener ga'
 'Salut sama pak ganjar apapun yang terjadi bakal terus dukung'
 'Pak Ganjar Mahfud pilihan yang tepat untuk m3nang ayo dukung GAMA terus'
 'bismillah semoga ganjar yang menang'
 'Perlu diingat juga bahwa dia satusatunya calon yang tidak pernah absen di pilpres sejak edisi'
 'Pilihan terbaik cuman ganjar Mahfud karena Ganjar Mahfud B3rsih'
 'Datangnya trus dukungan untuk Pak Anies mengisyaratkn akan kemenangan yg tak lama lgi'
 'Betul sekali PakbowoGibran YesBanget akan mendukung asupan yang memadai utk kesehatan optimal masa emas saat masa kehamilan dan batita MasyarakatBenci CaraFitnah'
 'Setujuu namanya saja pilpres bukan pilpres pilwapres'
 'Kritik gimik doangkakehan ndobos gw pikir punya idealisme krn pengikutnya banyakternyata oh ternyata'
 'Gimana kalo lomba ngaji antar

### Stemming Words

In [1]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [2]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [12]:
stemmed_contents_np = np.array([])
for content in cleaned_contents_np:
    stemmed_content = stemmer.stem(content)
    stemmed_contents_np = np.append(stemmed_contents_np, stemmed_content)

### Translate and Convert some slang words

In [7]:
from google.cloud import translate_v2 as translate

In [16]:
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'C:/Users/asus/OneDrive/Documents/Kuliah/Materi Kuliah/Semester 5/ML/UAS/ambient-scion-406902-a6d0c2b36a30.json'

In [9]:
#translation process (including slang term translation)
def translate_content(content):
    # Create a client using the authenticated service account
    translate_client = translate.Client()
    
    target_language = 'en'
    
    # Perform the translation
    translation = translate_client.translate(
        content,
        target_language=target_language
    )
    
    # Display the translated text
    return translation['translatedText']

#beberapa kata slang masih sering di misintepret oleh cloud translate API, bisa menggunakan Auto ML untuk projek selanjutnya

In [12]:
for i in range (0, cleaned_contents_np.size):    
    translated_content = translate_content(cleaned_contents_np[i])
    cleaned_contents_np[i] = translated_content 

In [13]:
from html import unescape
for i in range (0, cleaned_contents_np.size):    
    converted_string = unescape(cleaned_contents_np[i])
    cleaned_contents_np[i] = converted_string 

In [24]:
tweets_df

Unnamed: 0             tweet_id         username  \
0             0  1730587179322405120  Tokobarokahjaya   
1             1  1730587179041313024    rizkypuetraaa   
2             2  1730587178709958912       orangOedik   
3             3  1730587167003700992       luffyphile   
4             4  1730587163442708992     AiraGreselya   
..          ...                  ...              ...   
665         665  1730584689365434880  yosephermawan17   
666         666  1730584678493536000       Heraloebss   
667         667  1730578327289861120  AchmadShonnyArc   
668         668  1730584677403255040    trilestaritky   
669         669  1730584677055184896  RondangKomariah   

                                               content  retweets  likes  \
0    @ganjarpranowo wah pake penyambutan adat  , me...         0      0   
1    @TuaJalanJalan @sleepinight @PartaiSocmed @Tua...         0      0   
2    @ferizandra Bang jgn gt lah...coba kita tabayu...         0      0   
3    @tvOneNews Salut sama pak ganjar, apapun yang ...         0      0   
4    @tvOneNews Pak Ganjar Mahfud pilihan yang tepa...         0      0   
..                                                 ...       ...    ...   
665    @tvOneNews Kawall Ganjar Mahfud MD sampe m3nang         0      0   
666  Mohon izin Posting Video panjang Pak @prabowo ...        15     34   
667  @Heraloebss Just following digital record hone...         0      1   
668  @voiceofpkb Bersama pasangan Anies Muhaimin wu...         0      0   
669  Prabowo Cinta Rakyat Ketua TKD Jabar Ridwan Ka...         8      0   

     polarity sentiment  score  magnitude  
0           0  Positive    0.9        0.9  
1           0  Negative   -0.7        0.7  
2           0  Positive    0.1        0.1  
3           0  Positive    0.9        0.9  
4           0  Positive    0.9        0.9  
..        ...       ...    ...        ...  
665         0  Positive    0.4        0.4  
666         0  Negative   -0.3        0.3  
667         0  Positive    0.4        0.4  
668         0  Positive    0.7        0.7  
669         0  Positive    0.4        0.4  

[670 rows x 10 columns]

### Data Labelazitaion

In [17]:
from google.cloud import language_v1

def analyze_sentiment(text_content):
    client = language_v1.LanguageServiceClient()

    # Available types: PLAIN_TEXT
    type_ = language_v1.Document.Type.PLAIN_TEXT

    # Optional. If not specified, the language is automatically detected.
    language = "id"
    document = {"content": text_content, "type_": type_, "language": language}

    # Available values: NONE, UTF8, UTF16, UTF32
    encoding_type = language_v1.EncodingType.UTF32


    response = client.analyze_sentiment(request={'document': document, 'encoding_type': encoding_type})

    # Get the overall sentiment of the input document
    sentiment = response.document_sentiment

    return sentiment.score, sentiment.magnitude


In [18]:
scores= []
magnitudes = []
sentiments = []
for content in stemmed_contents_np:
    score, magnitude = analyze_sentiment(content)
    scores.append(score)
    magnitudes.append(magnitude)
    sentiment = "Positive" if score > 0 else "Neutral" if score == 0 else "Negative"
    sentiments.append(sentiment)

tweets_df['score'] = scores
tweets_df['magnitude'] = magnitudes
tweets_df['sentiment'] = sentiments

In [23]:
print(tweets_df)

     Unnamed: 0             tweet_id         username  \
0             0  1730587179322405120  Tokobarokahjaya   
1             1  1730587179041313024    rizkypuetraaa   
2             2  1730587178709958912       orangOedik   
3             3  1730587167003700992       luffyphile   
4             4  1730587163442708992     AiraGreselya   
..          ...                  ...              ...   
665         665  1730584689365434880  yosephermawan17   
666         666  1730584678493536000       Heraloebss   
667         667  1730578327289861120  AchmadShonnyArc   
668         668  1730584677403255040    trilestaritky   
669         669  1730584677055184896  RondangKomariah   

                                               content  retweets  likes  \
0    @ganjarpranowo wah pake penyambutan adat  , me...         0      0   
1    @TuaJalanJalan @sleepinight @PartaiSocmed @Tua...         0      0   
2    @ferizandra Bang jgn gt lah...coba kita tabayu...         0      0   
3    @tvOneNews

In [25]:
tweets_df.to_excel("tweetsfixindo.xlsx")

In [92]:
cleaned_contents_np

array(['wah pake penyambutan adat menggambarkan kalau pak ganjar di terima dengan baik',
       'lha gw ngedukung prabowo lalu dicap buzzer Wkwkwkwkw tuduhannya ga masuk akal tolol',
       'Bang jgn gt lahcoba kita tabayunbener ga',
       'Salut sama pak ganjar apapun yang terjadi bakal terus dukung',
       'Pak Ganjar Mahfud pilihan yang tepat untuk m3nang ayo dukung GAMA terus',
       'bismillah semoga ganjar yang menang',
       'Perlu diingat juga bahwa dia satusatunya calon yang tidak pernah absen di pilpres sejak edisi',
       'Pilihan terbaik cuman ganjar Mahfud karena Ganjar Mahfud B3rsih',
       'Datangnya trus dukungan untuk Pak Anies mengisyaratkn akan kemenangan yg tak lama lgi',
       'Betul sekali PakbowoGibran YesBanget akan mendukung asupan yang memadai utk kesehatan optimal masa emas saat masa kehamilan dan batita MasyarakatBenci CaraFitnah',
       'Setujuu namanya saja pilpres bukan pilpres pilwapres',
       'Kritik gimik doangkakehan ndobos gw pikir punya id

In [4]:
tweets_df = pd.read_excel("tweetsfixindo.xlsx")

In [26]:
X = stemmed_contents_np
y = np.array(sentiments)

### Encode Independent Variable

In [27]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
label_encoder = LabelEncoder()

# Fit and transform the labels
y = label_encoder.fit_transform(y)

print(y)

[2 0 2 2 2 2 2 2 2 1 1 0 2 1 0 0 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 1 0 2 2 2 2 2 2 2 0 2 0 2 1 2 0
 2 2 2 2 0 2 2 0 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 0 2 0 0 2 2 0 0 2 0 2 2 2
 2 2 2 2 2 0 2 2 1 2 2 0 2 2 1 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 0 2 0 2 2 2 0 2 2 2 0 2 2
 2 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 1 0 2 2 2 0 1 0 2 2 2 0 2 0 2 2
 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 1 0 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 0 1 2 0 2 2 1 0 0 1 2 2 2 0
 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 0 0 2 2 0 2 2 0 2 2 2 0 1 0 2 2 2 2
 2 2 2 2 2 0 2 2 1 2 1 2 2 2 2 2 0 0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 2 2 2 0 2 0 2 1 2 2 1 2 1 0 1 2 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 2 2 2 2 2 2 1 2 1 1 1 2 0 2 2 2 1 2 0 1 2 2 2 2 1 2 0 2 2 2 2 2
 2 2 2 2 2 2 2 1 2 0 2 2 

## Text Weighting using TF-IDF

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tfidf_vectorizer = TfidfVectorizer()
# Create the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the documents
tfidf_matrix = tfidf_vectorizer.fit_transform(stemmed_contents_np)

# Get the feature names (words)
feature_names = tfidf_vectorizer.get_feature_names_out()

# Create a DataFrame to display the TF-IDF matrix
df_tfidf = pd.DataFrame(data=tfidf_matrix.toarray(), columns=feature_names)
# print(df_tfidf)
np_tfidf = df_tfidf.to_numpy()
print(np_tfidf.shape)

(670, 2383)


## Splitting Data into Training Data and Test Data

In [31]:
from sklearn.model_selection import StratifiedShuffleSplit

In [70]:
sss = StratifiedShuffleSplit(n_splits=1, train_size=0.7, test_size=0.3,random_state=42)

In [72]:
for train_index, test_index in sss.split(np_tfidf, y):
    X_train, X_test = np_tfidf[train_index], np_tfidf[test_index]
    y_train, y_test = y[train_index], y[test_index]

## Classification Analysis

### Naive Bayes

In [3]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [2]:
np_acc = []

In [41]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [48]:
from sklearn.naive_bayes import GaussianNB

In [73]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
acc = 100*accuracy_score(y_test,ypred)
print(acc)

75.62189054726367


### SVM

In [74]:
from sklearn.svm import SVC

In [90]:
svm_classifier = SVC(kernel='linear', C=4.0)
svm_classifier.fit(X_train, y_train)
y_pred = svm_classifier.predict(X_test)
accuracy = 100 * accuracy_score(y_test, y_pred)
print(accuracy)

80.59701492537313


### ANN

In [76]:
from sklearn.svm import SVC

In [77]:
from sklearn.neural_network import MLPClassifier
r1=2
r2 = 2
max_f1 = 0
max_acc=0
for nh in range(2,100):
  ann=MLPClassifier(hidden_layer_sizes=nh, max_iter=12000, random_state=42)
  ann.fit(X_train,y_train)
  acc = 100*ann.score(X_test,y_test)
  #f1 fold evaluation
  ypred = ann.predict(X_test)
  f1 = f1_score(y_test, y_pred, average='weighted') *100
  if(acc>max_acc):
    r1=nh
    max_acc=acc
  # print('Neuron in hidden layer (original data): %g, accuracy %.2f %%, f1_score %.2f %%'%(nh,acc,f1))

  if(f1>max_f1):
    r2 = nh
    max_f1 = f1

print('Optimum hidden layer for accuracy:' ,r1)
print('Maximum accuracy %g %%'%max_acc)
print('Optimum hidden layer for f1 score:' ,r2)
print('Maximum f1 score %g %%'%max_f1)

Optimum hidden layer for accuracy: 6
Maximum accuracy 82.0896 %
Optimum hidden layer for f1 score: 2
Maximum f1 score 73.1456 %


### Logistic Regression

In [78]:
from sklearn.linear_model import LogisticRegression

In [95]:
logr=LogisticRegression(multi_class='multinomial', C=3.0)
logr.fit(X_train, y_train)
ypred=logr.predict(X_test)
acc = 100*accuracy_score(y_test, ypred)
print(acc)

79.60199004975125


## Dimesion Reduction

In [96]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=1000)  # Adjust the number of components
tfidf_reduced = svd.fit_transform(tfidf_matrix)
print(tfidf_reduced.shape)

(670, 670)


In [97]:
for train_index, test_index in sss.split(tfidf_reduced, y):
    X_train_reduced, X_test_reduced = tfidf_reduced[train_index], tfidf_reduced[test_index]
    y_train_reduced, y_test_reduced = y[train_index], y[test_index]

In [99]:
gnb = GaussianNB()
gnb.fit(X_train_reduced,y_train_reduced)
ypred_reduced = gnb.predict(X_test_reduced)
acc = 100*accuracy_score(y_test_reduced,ypred_reduced)
print(acc)

50.24875621890548


In [164]:
print(tfidf_matrix.shape)

(670, 2936)


In [187]:
from umap import UMAP

umap_model = UMAP(n_components=1000)
tfidf_umap = umap_model.fit_transform(tfidf_matrix)

ImportError: cannot import name 'UMAP' from 'umap' (C:\Users\asus\anaconda3\envs\jupyter_python_3114\Lib\site-packages\umap\__init__.py)

In [97]:
print(scores)

[0.8999999761581421, -0.6000000238418579, 0.0, 0.8999999761581421, 0.8999999761581421, 0.800000011920929, 0.5, 0.800000011920929, 0.8999999761581421, 0.699999988079071, 0.0, 0.10000000149011612, 0.30000001192092896, 0.10000000149011612, 0.20000000298023224, 0.4000000059604645, 0.4000000059604645, 0.4000000059604645, 0.4000000059604645, 0.6000000238418579, 0.5, 0.30000001192092896, 0.4000000059604645, 0.4000000059604645, 0.800000011920929, 0.30000001192092896, 0.699999988079071, 0.6000000238418579, 0.5, 0.5, 0.5, 0.8999999761581421, 0.4000000059604645, 0.800000011920929, 0.699999988079071, 0.30000001192092896, 0.800000011920929, 0.8999999761581421, 0.10000000149011612, 0.4000000059604645, 0.800000011920929, 0.10000000149011612, 0.8999999761581421, 0.8999999761581421, 0.20000000298023224, 0.800000011920929, 0.4000000059604645, 0.8999999761581421, 0.8999999761581421, 0.30000001192092896, 0.8999999761581421, 0.10000000149011612, 0.30000001192092896, -0.20000000298023224, 0.8999999761581421

In [ ]:
label = ['Naive Bayes', 'SVM', 'ANN', 'Logistic Regression']
plt.bar(label, np_acc)